name: Deploy to EC2

on: 
  push: 
    branch: main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-lastest

    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: '20.11'
        
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
      
      - name: Achive build files
        run: zip -r dist.zip dist

      - name: Copy file to ec2
        uses: appleboy/scp-action@v0.1.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist.zip"
          target: "home/ubuntu/shop_now/dist.zip"
        
      - name: Deploy EC2
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: | 
            cd /home/ubuntu/shop_now
            if [ -d "dist" ]; then
              rm -rf dist
            fi
            uzip -o dist.zip
            pm2 restart all 
            sudo systemctl restart nginx